### ISSUE TITLE
Multi Part Causing Loop

### ISSUE THREAD

**Issue by jason-fitzsimmons** [aws-samples/accelerated-data-lake#1]
I have been working on implementing the accelerated data lake and was having an issue with larger files that were using the multipart upload.

Once the process hit the staging-engine-AttachTagsAndMetaDataToFi Lambda step it would start the whole process again for the same file over and over again.  If I disabled the multipart upload through the AWS CLI and uploaded a large file then the process went through fine.  After some testing I was able to lock it down to this section in the Lambda

`        s3.copy(
            copy_source,
            bucket,
            key,
            ExtraArgs={
                "Metadata": metadata,
                "MetadataDirective": "REPLACE"
            }
        )
`

Changing it to this has stopped the looping problem

`
s3.copy_object(
    Bucket =bucket, 
    Key = key, 
    CopySource = copy_source, 
    Metadata = metadata, 
    MetadataDirective='REPLACE'
)
`

**Comment by tpbrogan** [comment]
This will be fixed with the tags and metadata now attached when the file / object is moved to staging (so no copy within the raw bucket as metadata is attached). Thanks for pointing this out.
