### ISSUE TITLE
Visulation Template File

### ISSUE THREAD

**Issue by jason-fitzsimmons** [aws-samples/accelerated-data-lake#2]
When generating the Visulation Lambdas `sam package --template-file ./lambdaDeploy.yaml --output-template-file lambdaDeployCFN.yaml`

The template file created has and incorrect TemplateFormatVersion line at the end of the file and wont deploy

> "\xEF\xBB\xBFAWSTemplateFormatVersion": '2010-09-09')

When changed to 

> "AWSTemplateFormatVersion": '2010-09-09')

I was able to deploy.  This was also happening for the Staging Engine as well but when I downloaded the latest version yesterday the Staging Engine template didn't have that problem

**Comment by tpbrogan** [comment]
Fixed - there was a byte order mark on the lambdaDeploy file which affected windows installations. Thanks for pointing this out.
