### ISSUE TITLE
Acceptable error threshold [Enhancement]

### ISSUE THREAD

**Issue by sukenshah** [aws-samples/accelerated-data-lake#5]
### What is an error threshold?
The accelerated data lake framework follows strict validation policy. The data file is considered failed if there is even a single validation error. The error threshold is a mechanism to allow an acceptable number of validation errors per data file.

### Does error threshold apply to all validations?
The error threshold only applies to semantic validation rules e.g. number ranges, enumeration values etc. The data file is rejected if there are syntactic errors.

### How is error threshold configured?
The error threshold can be configured via the data source config file. The error threshold is represented as % of allowed errors per total number of records in a file.

### Where do I need error threshold?
The error threshold can be useful when dealing with low quality data files. With error threshold, the  customers can still build the data lake without having to correct the errors for each files.

cc @paulmacey1 @tpbrogan

**Comment by tpbrogan** [comment]
Validation / data quality is a huge subject and there is no "one size fits all" approach. The accelerated data lake schema checking can be as strict or as forgiving as the user requires, but if the user's schema validation fails then the object is moved to the failed bucket. This is the correct approach as even a small percentage of input data having an invalid schema can have adverse later on when querying the data. 

To test for low quality data, the data can be staged with schema validation that is as strict as the user requires, then Amazon's [Deequ](https://aws.amazon.com/blogs/big-data/test-data-quality-at-scale-with-deequ/) ran against the data.
